version: "3"

services:
  postgres:
    image: postgres:14.2
    container_name: flowbuild_db
    restart: always
    env_file:
      - ./.env.docker
    ports:
      - 5432:5432

  app:
    image: node:17.4
    env_file:
      - ./.env.docker
    container_name: flowbuild_app
    restart: on-failure:10 # necessary due to possibility of postgres not being ready when service runs
    depends_on:
      - postgres
    ports:
      - 3000:3000
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    working_dir: /usr/app
    #command: ./scripts/start_dev.sh
    #command: bash -c " npm install && npm rebuild && npm run migrations && npm run seeds && npm run start "
    command: bash -c " npm install && npm run migrations && npm run seeds && npm run tests "

  socket:
    image: hivemq/hivemq4:latest
    container_name: flowbuild_mqtt
    restart: on-failure:10
    ports:
      - 8081:8080
      - 1883:1883
      - 8000:8000

  auth:
    image: registry.supertokens.io/supertokens/supertokens-postgresql
    container_name: flowbuild_auth
    restart: always
    ports: 
      - 3567:3567

  nginx:
    image: nginx:latest
    container_name: flowbuild_nginx
    restart: always
    ports:
      - 8080:8080
      - 8082:8082
      - 443:443
    volumes:
      - ./nginx/reverse_proxy.conf:/etc/nginx/conf.d/default.conf
    networks:
      - flowbuild_auth
      - flowbuild_mqtt
      - flowbuild_app

networks:
  flowbuild_app:
  flowbuild_auth:
  flowbuild_mqtt: